### ISSUE TITLE
Cleanup uses of `open`

### ISSUE THREAD

**Issue by alberdingk-thijm** [princedpw/nv#5]
Right now, nv's source contains a lot of `open` calls at the start of each module. This makes it hard to find where a given function is defined and hard to read and edit the code. The section ["Opening Modules"](https://dev.realworldocaml.org/files-modules-and-programs.html) in Real World OCaML provides some recommendations on the subject.

Running `ripgrep -c "open" src/` in the `partitions` branch returns the following counts:
```
src/Syntax.mli:3
src/Syntax.ml:4
src/Input.ml:2
src/Main_defs.ml:20
src/Failures.ml:3
src/Lexer.mll:4
src/Quickcheck.ml:4
src/AbstractionMap.ml:3
src/Quickcheck.mli:3
src/Main.ml:2
src/Srp.mli:4
src/Typing.ml:6
src/Srp.ml:6
src/Interp.ml:4
src/Console.ml:2
src/AbstractionMap.mli:1
src/Input.mli:1
src/Parser.mly:3
src/Interp.mli:2
src/Slicing.ml:3
src/Solution.ml:3
src/Solution.mli:2
src/Globals.ml:1
src/OptimizeBranches.ml:1
src/transformations/UnboxOptions.ml:4
src/transformations/RecordUnrolling.mli:1
src/transformations/Inline.ml:2
src/transformations/Renaming.ml:3
src/transformations/ToEdge.ml:1
src/transformations/tnf.ml:3
src/transformations/Inline.mli:1
src/transformations/Renaming.mli:2
src/transformations/RecordUnrolling.ml:3
src/transformations/TupleFlatten.ml:3
src/Abstraction.ml:11
src/datastructures/IMap.ml:2
src/datastructures/Collections.ml:1
src/smt/SmtExprEncodings.ml:4
src/smt/SmtCheckProps.ml:7
src/datastructures/QueueSet.ml:1
src/smt/SmtLang.ml:2
src/datastructures/AdjGraph.ml:2
src/smt/SMTParser.mly:2
src/smt/SmtSrp.ml:3
src/smt/SmtHiding.ml:12
src/smt/SmtUtils.ml:3
src/datastructures/IMap.mli:1
src/smt/SmtModel.ml:7
src/smt/Smt.ml:11
src/smt/SmtEncodings.ml:7
src/BDD/BddFunc.ml:2
src/BDD/BddUtils.ml:2
src/partitioning/Partition.mli:3
src/BDD/BddFunc.mli:2
src/utils/Generators.ml:5
src/smt/SmtOptimizations.ml:3
src/utils/Printing.mli:1
src/utils/Printing.ml:2
src/utils/Wellformed.mli:1
src/BDD/BddMap.ml:4
src/utils/RecordUtils.ml:1
src/utils/Visitors.mli:1
src/utils/Wellformed.ml:3
src/utils/Generators.mli:2
src/utils/Visitors.ml:1
src/BDD/BddMap.mli:2
src/transformations/mapUnrolling/MapUnrolling.ml:1
src/utils/RecordUtils.mli:1
src/transformations/mapUnrolling/MapUnrollingConversion.ml:5
src/utils/Memoization.ml:1
src/transformations/mapUnrolling/MapUnrollingGuts.ml:3
src/transformations/mapUnrolling/MapUnrolling.mli:1
src/smt/SMTLexer.mll:2
src/transformations/mapUnrolling/MapUnrollingUtils.ml:2
src/transformations/mapUnrolling/MapUnrollingCleanup.ml:1
```

It would be useful to go through these files and replace uses of `open` where the source file is *(a)* not immediately obvious; and *(b)* providing fairly specific utilities with `open` statements closer to the point of use, or simply avoiding calling `open` altogether.

**Comment by DKLoehr** [comment]
There was some discussion on this topic during #6, but since this is still open:
Since the switch to dune, I've worked with some of the files where opens were localized or not used (instead prefixing uses with their module path). I'm finding that I have a lot more trouble reading the latter: having to open the module in each function adds excess lines, and not using opens leads to extremely long names. All of this makes it harder to look at the code and understand what it's doing, which I value highly.

To use a common example, it's much, much easier for me to understand
`oget`
than it is for me to understand
`Nv_utils.OCamlUtils.oget.`
oget in particular is a very common utility function that doesn't have much meaning. If I just see "oget" I basically ignore it; if I see "Nv_utils.OCamlUtils.oget" I have to spend effort looking at it to verify that it's unimportant.

Having top-level opens does make it harder for new people to read the code, since that usually requires going to a lot of definition sites to see exactly what functions do. But as Nick mentioned in #6, merlin has functionality for doing just that. Our naming conventions are also good at avoiding overlap, so I'm not worried about ambiguity or cluttering the global namespace.

**Comment by alberdingk-thijm** [comment]
@DKLoehr I think I'm coming around to this as I get more familiar with the code. There are undoubtedly a few cases where it's nice to have a little more clarity through the namespace: I think the even nicer choice than `oget x` would be `Option.get x` or `x.get`, using [`BatOption`](https://ocaml-batteries-team.github.io/batteries-included/hdoc2/BatOption.html); I would also say for some very large modules like `Syntax`, a helpful best practice is to use the module name (especially given potential conflicts with `SMT`).

But given the fact that merlin gives you most of the lookup to figure things out for free in an editor-generic way, I think we can safely close this issue now.
